<?php
/**
 * Created by PhpStorm.
 * User: a_kerroumi
 * Date: 30/11/2016
 * Time: 10:46
 */

namespace App\Exceptions;

use Psr\Http\Message\ResponseInterface as PsrResponseInterface;
use Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory;
use Symfony\Component\HttpFoundation\Response as SymfonyResponse;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

/*
 * This trait handles errors returned by the "docmanager_api" API
 */
trait DocManagerApiExceptionHandler
{
    public function handleApiResponse($response)
    {
        if ($response instanceof PsrResponseInterface)
        {
            $response = (new HttpFoundationFactory)->createResponse($response);
        }
        elseif (! $response instanceof SymfonyResponse)
        {
            $response = new Response($response);
        }
        elseif ($response instanceof BinaryFileResponse)
        {
            $response = $response->prepare(Request::capture());
        }
        $response = json_decode($response->getContent(), true);
        /*
         * If the http request to the API has been successful or it came back with an error destined to be displayed
         * to the end user, the response is returned other wise a custom error page is generated by the
         * displayErrorPage() function
         */
        if($response['success'] || $response['error_type'] == 'docmanager_user_error')
        {
            return $response;
        }
        else
        {
            $this->displayErrorPage($response);
        }
    }

    /*
     * When a request to the API comes back with an error, this function enables to display the error in
     * a custom error page
     */
    public function displayErrorPage($response)
    {
        $errorData = [];
        $debug = env('APP_DEBUG');
        if($debug)
        {
            if($response['error_type'] == 'docmanager_api_error')
            {
                $errorData['code'] = $response['code'];
                $errorData['status'] = $response['status'];
                $errorData['hint'] = $response['hint'];
                $errorData['message'] = "Error message from API - " . $response['hint'];
            }
            else if($response['error_type'] == 'php_error')
            {
                $errorData['status'] = $response['status'];
                $errorData['message'] = "Error message from API - " . $response['message'];
                $errorData['error_file'] = $response['error_file'];
                $errorData['error_line'] = $response['error_line'];
                $errorData['error_trace_string'] = $response['error_trace_string'];
            }
        }
        $errorData = json_encode($errorData, true);
        switch($status = $response['status'])
        {
            //Server Error
            case ($status / 100 == 5):
                abort(500, $errorData);
                break;
            //Unauthorized (Authentication or permission pb)
            case 401:
                abort(401, $errorData);
                break;
            default:
                abort(404, $errorData);
        }
    }
}